project:
  name: "customer-churn-prediction"
  version: "1.0.0"

data:
  path: "../../data/WA_Fn-UseC_-Telco-Customer-Churn.csv"
  test_size: 0.2
  random_state: 42
  target_column: "Churn"

model:
  type: "xgboost"
  params:
    n_estimators: 150
    max_depth: 7
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42

mlflow:
  tracking_uri: "http://mlflow:5000"
  experiment_name: "Churn_Prediction"
  registered_model_name: "churn_xgboost_prod"
  artifact_store: "s3://mlflow-artifacts"

thresholds:
  accuracy_min: 0.80
  roc_auc_min: 0.80
  f1_score_min: 0.75

monitoring:
  retrain_frequency_days: 7
  performance_check_frequency_days: 1
